name: placeholder_Name

on:
  pull_request:
    branches: branch-name
  push:
    branches:
      - branch-1

jobs:
  build:
    strategy:
      matrix:
        java: [17]  
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        with:
          key: key
        # java-version: ${{ matrix.java }}
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version : ${{ matrix.java }}
          distribution : 'adopt'

      - name: Build with Maven
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
