name: placeholder_Name

on:
  pull_request:
    branches: branch-name
  push:
    branches:
      - branch-1

jobs:
  build:
    strategy:
      matrix:
        java: [17]  
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        with:
          key: key
        # java-version: ${{ matrix.java }}
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version : ${{ matrix.java }}
          distribution : 'adopt'

      - name: Build with Maven
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

      - name: Elasticsearch
        run: |
          sudo rm -rf /var/lib/elasticsearch
          curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.3-amd64.deb -o elasticsearch.deb
          sudo dpkg -i --force-confnew elasticsearch.deb
          sudo cp ./src/test/resources/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
          sudo cat /etc/elasticsearch/elasticsearch.yml
          sudo java -version
          sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
          sudo service elasticsearch start
          sleep 30  
