name: placeholder_Name

on:
  pull_request:
    branches: branch-name
  push:
    branches:
    - branch-1

jobs:
  build:
    strategy:
      matrix: java
  - name: Placeholder
    runs-on: ubuntu-latest
    steps:
      with: key
      with:
        java-version: 1.8
      with: java-version
    - name: placeholder_Name
      uses: actions/checkout@version
      with:
        java-version: ${{ matrix.java }}
      uses: actions/setup-java@version
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

