name: Manual Workflow Migration

on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [openjdk17]        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}


      
