name: Manual Workflow Migration

on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Elasticsearch
        run: |
          sudo rm -rf /var/lib/elasticsearch
          curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.3-amd64.deb -o elasticsearch.deb
          sudo dpkg -i --force-confnew elasticsearch.deb
          sudo cp ./src/test/resources/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
          sudo cat /etc/elasticsearch/elasticsearch.yml
          sudo java -version
          sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
          sudo service elasticsearch start
          sleep 30



      
